const TEAM_NAMES = { procurement:'Local SOA', india_procurement:'Indian SOA', corporate_security:'Corporate Security', vendor:'Vendor' };
const ROLE_MARKS = { procurement:'LS', india_procurement:'IS', corporate_security:'CS', vendor:'V' };
const STAGE_LABELS = { VENDOR:'Awaiting vendor', LOCAL:'Local SOA review', TRANSLATION:'Translating documents', INDIA:'Indian SOA review', SECURITY:'Corporate Security review', LOCAL_REWORK:'Legacy rework', COMPLETED:'Approved' };
function mapTicket(t) {
  if (!t.workflowStage) throw new Error('The backend is running an older version. Restart the backend on port 3000, then refresh and sign in again.');
  return { id:t.ticketNumber, name:t.vendorName, authorizedPersonName:t.authorizedPersonName, email:t.vendorEmail, address:t.address, country:COUNTRY_BY_CODE[t.countryCode]||t.countryCode, language:t.language, stage:t.workflowStage, status:STAGE_LABELS[t.workflowStage]||t.status, created:t.createdAt, history:t.history||[], docs:t.documents.map(d=>({ id:d.id,name:d.name,status:d.status==='LOCAL_PROCUREMENT_ACCEPTED'?'Approved':d.status==='DOCUMENTS_UPLOADED'?'Uploaded':d.rejectionReason?'Rejected':'Requested',indiaStatus:d.indiaStatus,securityStatus:d.securityStatus,version:d.version||0,note:d.rejectionReason||'',fileName:d.fileName||'',uploadId:d.latestUploadId,translation:d.translation||null })) };
}
function sidebar() { return `<aside class="side"><div class="brand"><div class="brand-mark">C</div><div>Cognizant<small>Vendor onboarding</small></div></div><nav class="nav"><button class="active" id="refreshDashboard"><span class="icon">⌂</span><span>Refresh dashboard</span></button>${['vendor','india_procurement'].includes(state.role)?`<button id="outboxBtn"><span class="icon">✉</span><span>Mail outbox (${state.mails.length})</span></button>`:''}</nav><div class="side-bottom"><div class="user-mini"><div class="avatar">${ROLE_MARKS[state.role]}</div><div><b>${TEAM_NAMES[state.role]}</b><small>${esc(state.user)}</small></div></div><button id="logout" class="btn ghost" style="width:100%;margin-top:14px">Sign out</button></div></aside>`; }
function portal() { const soa=['procurement','india_procurement'].includes(state.role); const home=state.role==='vendor'?vendorHome(state.tickets):state.role==='india_procurement'?procHome():reviewHome(); return `<div class="shell">${sidebar()}<main class="main"><header class="top"><div class="workspace-heading"><h1 class="workspace-title">${TEAM_NAMES[state.role]} workspace</h1>${soa?'<span class="workspace-subtitle">Supplier Onboarding &amp; Administration</span>':''}</div><span class="pill">● Secure session</span></header><div class="content">${home}</div></main></div>`; }
function reviewHome() {
  const stage = { procurement:'LOCAL', india_procurement:'INDIA', corporate_security:'SECURITY' }[state.role];
  const ready = state.tickets.filter(t=>t.stage===stage);
  return `<section class="hero"><div><div class="eyebrow">${TEAM_NAMES[state.role]}</div><h2>Document review queue</h2><p>Review the available documents. Rejected documents are sent directly to the vendor for correction.</p></div></section><div class="card metric"><strong>${ready.length}</strong><span>Requests awaiting your team</span></div>${ticketTable(ready,true)}<details><summary>All requests (including returned and completed)</summary>${ticketTable(state.tickets.filter(t=>t.stage!==stage),true)}</details>`;
}
function flowDashboard(t) {
  const all = fn => t.docs.length>0 && t.docs.every(fn);
  const steps = [ ['REQUEST','Indian SOA request',true], ['VENDOR','Vendor upload',all(d=>!['Requested','Rejected'].includes(d.status))], ['LOCAL','Local SOA',all(d=>d.status==='Approved')], ['TRANSLATION','English translation',all(d=>d.status==='Approved'&&d.translation?.status==='COMPLETED')], ['INDIA','Indian SOA',all(d=>d.indiaStatus==='APPROVED')], ['SECURITY','Corporate Security',t.stage==='COMPLETED'], ['COMPLETED','Complete',t.stage==='COMPLETED'] ];
  return `<section aria-label="Request flow" style="margin:20px 0"><h3>Request flow</h3><p><b>Current step: ${esc(t.status)}</b></p><ol class="flow-steps">${steps.map(([key,label,done])=>`<li class="flow-step ${done?'flow-done':key===t.stage?'flow-current':''}"><span>${done?'✓ Completed':key===t.stage?'● Current':'○ Pending'}</span><b>${label}</b></li>`).join('')}</ol><p class="flow-route-note"><b>Correction route:</b> Indian SOA or Corporate Security rejection → Vendor → Local SOA → translation → return to the rejecting team.</p><details><summary>Review and upload history (${t.history.length})</summary>${t.history.map(e=>{let details=e.details;try{if(typeof details==='string')details=JSON.parse(details)}catch{details={}}return `<div style="padding:8px;border-bottom:1px solid var(--line)"><b>${esc(e.stage)} · ${esc(e.action.replaceAll('_',' '))}</b><br><small>${esc(e.actor_email)} · ${esc(new Date(e.created_at).toLocaleString())}</small>${Array.isArray(details)?details.map(d=>`<div>${esc(d.name||'Document '+d.documentId)}: ${esc(d.decision||'Replacement requested')}${d.reason?' — '+esc(d.reason):''}</div>`).join(''):details.version?`<div>Document ${esc(details.documentId)} · version ${esc(details.version)}</div>`:''}</div>`}).join('')||'<p>No new workflow events yet.</p>'}</details></section>`;
}
function procTicket(t) {
  const stageForRole={procurement:'LOCAL',india_procurement:'INDIA',corporate_security:'SECURITY'};
  const canReview=t.stage===stageForRole[state.role];
  const eligible=d=>canReview&&(t.stage==='LOCAL'?d.status==='Uploaded':d.status==='Approved'&&d.translation?.status==='COMPLETED'&&(t.stage==='INDIA'?d.indiaStatus:d.securityStatus)==='PENDING');
  const rows=t.docs.map(d=>`<div class="doc-row"><input aria-label="Select ${esc(d.name)}" class="reviewSelect" type="checkbox" data-doc="${d.id}" ${eligible(d)?'':'disabled'}><div><p>${esc(d.name)} · v${d.version}</p><small>${esc(d.fileName)}<br>Local: ${esc(d.status)} · India: ${esc(d.indiaStatus)} · Security: ${esc(d.securityStatus)}</small>${d.note?`<p style="color:var(--red)">Rejection reason: ${esc(d.note)}</p>`:''}<br><small>English translation: ${esc(d.status==='Approved'?(d.translation?.status||'Not started'):'Available after Local SOA approval')}${d.status==='Approved'&&d.translation?.error?' — '+esc(d.translation.error):''}</small><div class="field rejectionReason hidden" data-reason-for="${d.id}"><label>Reason for rejecting ${esc(d.name)}</label><textarea maxlength="1000" rows="2"></textarea></div></div><div class="doc-actions">${d.uploadId?`<button class="mini viewDoc" data-upload="${d.uploadId}">View Original</button>`:''}${d.status==='Approved'&&d.translation?.status==='COMPLETED'?`<button class="mini viewTranslation" data-translation="${d.translation.id}">View English</button>`:''}<button class="mini approve setDecision" data-doc="${d.id}" data-decision="APPROVED" ${eligible(d)?'':'disabled'}>Approve</button><button class="mini reject setDecision" data-doc="${d.id}" data-decision="REJECTED" ${eligible(d)?'':'disabled'}>Reject</button></div></div>`).join('');
  const m=modal(`<div class="modal" style="max-width:1000px"><div class="modal-head"><div><div class="eyebrow">${esc(t.id)} · ${esc(t.country)}</div><h3>${esc(t.name)}</h3></div><button class="close">×</button></div><div class="modal-body"><div class="form-grid"><div><small>OWNER / AUTHORIZED PERSON</small><br><b>${esc(t.authorizedPersonName||'Not provided')}</b></div><div><small>VENDOR EMAIL</small><br>${esc(t.email)}</div><div><small>COMMUNICATION</small><br>${esc(t.language)}</div><div><small>REGISTERED ADDRESS</small><br>${esc(t.address)}</div></div>${flowDashboard(t)}<h3>${TEAM_NAMES[state.role]} document review</h3><div class="docs">${rows}</div></div><div class="modal-foot"><button data-close class="btn ghost">Close</button><button id="refreshRequest" class="btn ghost">Refresh status</button>${state.role==='procurement'&&t.stage==='TRANSLATION'?'<button id="retryTranslation" class="btn secondary">Retry translations</button>':''}${canReview?'<button id="saveReview" class="btn primary">Submit review</button>':''}</div></div>`);
  const decisions={};
  m.querySelectorAll('.setDecision').forEach(b=>b.onclick=()=>{if(!m.querySelector(`.reviewSelect[data-doc="${b.dataset.doc}"]`).checked)return toast('Select the document checkbox first');decisions[b.dataset.doc]=b.dataset.decision;b.parentElement.querySelectorAll('.setDecision').forEach(x=>x.style.background='');b.style.background=b.dataset.decision==='APPROVED'?'#e5f7f0':'#fff0f2';m.querySelector(`.rejectionReason[data-reason-for="${b.dataset.doc}"]`).classList.toggle('hidden',b.dataset.decision!=='REJECTED')});
  m.querySelectorAll('.viewDoc').forEach(b=>b.onclick=()=>openFile(`/uploads/${b.dataset.upload}`));
  m.querySelectorAll('.viewTranslation').forEach(b=>b.onclick=()=>openFile(`/translations/${b.dataset.translation}`));
  const refresh=async()=>{await loadData();m.remove();render();openTicket(t.id)};
  m.querySelector('#refreshRequest').onclick=()=>refresh().catch(e=>toast(e.message));
  const post=async(button,suffix,body)=>{button.disabled=true;try{await api(`/tickets/${encodeURIComponent(t.id)}/${suffix}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{})});await refresh();toast('Request updated. Check the current step and mail outbox.')}catch(e){button.disabled=false;toast(e.message)}};
  m.querySelector('#retryTranslation')?.addEventListener('click',e=>post(e.target,'translations/retry'));
  m.querySelector('#saveReview')?.addEventListener('click',e=>{const selected=[...m.querySelectorAll('.reviewSelect:checked')];if(!selected.length)return toast('Select at least one document');const payload=[];for(const cb of selected){const decision=decisions[cb.dataset.doc];if(!decision)return toast('Choose Approve or Reject for every selected document');const note=decision==='REJECTED'?m.querySelector(`.rejectionReason[data-reason-for="${cb.dataset.doc}"] textarea`).value.trim():'';if(decision==='REJECTED'&&!note)return toast('Add a separate reason for every rejected document');payload.push({documentId:Number(cb.dataset.doc),uploadId:t.docs.find(d=>String(d.id)===cb.dataset.doc).uploadId,decision,note})}post(e.target,'review',{decisions:payload})});
}
document.addEventListener('click',e=>{if(e.target.closest('#refreshDashboard'))loadData().then(render).catch(e=>toast(e.message))});
