const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
test('role dashboards and request controls reflect the active workflow stage',()=>{
  const root=path.join(__dirname,'../..');
  const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
  const context=vm.createContext({document:{addEventListener(){}},console});
  vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],context);
  vm.runInContext(fs.readFileSync(path.join(root,'workflow-ui.js'),'utf8'),context);
  for(const role of ['procurement','india_procurement','corporate_security','vendor']){
    const output=vm.runInContext(`state.role='${role}';state.user='test@example.test';portal()`,context);
    assert.match(output,/workspace/);
    assert.match(output,/workspace-title/);
    assert.equal(output.includes('id="newVendor"'),role==='india_procurement');
  }
  assert.match(vm.runInContext("state.role='procurement';portal()",context),/Local SOA workspace[\s\S]*Supplier Onboarding &amp; Administration/);
  assert.match(vm.runInContext("state.role='india_procurement';portal()",context),/Indian SOA workspace[\s\S]*Supplier Onboarding &amp; Administration/);
  vm.runInContext(`let rendered='';modal=inner=>{rendered=inner;return {querySelectorAll:()=>[],querySelector:()=>({addEventListener(){}})}};const sample={id:'T',name:'Demo',country:'Mexico',history:[],stage:'INDIA',status:'Indian SOA review',docs:[{id:1,name:'Tax',status:'Approved',version:1,uploadId:1,indiaStatus:'PENDING',securityStatus:'PENDING',translation:{id:1,status:'COMPLETED'}}]};`,context);
  const display=(role,stage)=>vm.runInContext(`state.role='${role}';sample.stage='${stage}';procTicket(sample);rendered`,context);
  const indiaReview=display('india_procurement','INDIA');
  assert.match(indiaReview,/id="saveReview"/);
  assert.match(indiaReview,/View English/);
  assert.doesNotMatch(display('procurement','INDIA'),/id="saveReview"/);
  assert.doesNotMatch(display('procurement','VENDOR'),/id="requestReplacements"/);
  vm.runInContext("sample.docs[0].indiaStatus='APPROVED'",context);
  const securityReview=display('corporate_security','SECURITY');
  assert.match(securityReview,/id="saveReview"/);
  assert.match(securityReview,/View English/);
  const completed=display('corporate_security','COMPLETED');
  assert.doesNotMatch(completed,/id="saveReview"/);
  assert.match(completed,/View Original/);assert.match(completed,/View English/);
  assert.match(completed,/flow-done/);
  vm.runInContext("sample.docs[0].status='Uploaded'",context);
  const local=display('procurement','LOCAL');
  assert.match(local,/class="reviewSelect"[^>]*data-doc="1"\s*>/);
  assert.match(local,/data-decision="APPROVED"\s*>Approve/);
  assert.match(local,/data-decision="REJECTED"\s*>Reject/);
  assert.match(local,/id="saveReview"/);
  assert.doesNotMatch(local,/View English/);
  assert.match(local,/Available after Local SOA approval/);
  vm.runInContext("sample.stage='VENDOR';sample.docs=[{id:1,name:'Pending tax document',status:'Requested'},{id:2,name:'Already uploaded address',status:'Uploaded'},{id:3,name:'Approved document',status:'Approved'}];vendorTicket(sample)",context);
  const vendor=vm.runInContext('rendered',context);
  assert.match(vendor,/Pending tax document/);
  assert.doesNotMatch(vendor,/Already uploaded address|Approved document|Request flow|Review and upload history/);
  vm.runInContext("sample.docs=[];vendorTicket(sample)",context);
  assert.match(vm.runInContext('rendered',context),/No documents are currently awaiting upload/);
  assert.throws(()=>vm.runInContext("mapTicket({status:'DOCUMENTS_UPLOADED'})",context),/older version/);
});
